Fix admin calendar
hpi-schul-cloud/schulcloud-calendar pull request #130
Opened 2023-02-08 20:58 UTC by wiaderwek

# Description

## Links to Tickets or other pull requests
https://ticketsystem.dbildungscloud.de/browse/BC-3170

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2023-02-09 08:33 UTC, MateuszSapalaPassCon approved these changes

2023-02-09 11:05 UTC, CeEv requested changes

2023-02-09 11:05 UTC, CeEv commented on src/routes/events.js
> +	authorizeAccessToScopeIdForDelete(user, scopeId)
I am not total fine with this change. It should only exists 2 types of checks. One for hasReadAccess and one for hasWriteAccess. Both should be already exists. In the end this both should mapped to one single function that check the data structure with the input of 'can-write', 'can-read' as parameter.

I am fine with the fact that the change on this place from read to write can be make sense.
Also that you add a named (delete) wrapper around the write check. 

But authorizeAccessToScopeIdForDelete is added instead of the existing methods. Maybe it is simpler ok, but it exists not really a need for this.

2023-02-09 11:05 UTC, CeEv commented on src/routes/events.js
> +	authorizeAccessToScopeIdForDelete(user, scopeId)
Can you please add a test to events.integration.test.js?

2023-02-10 06:29 UTC, CeEv approved these changes

2023-02-20 08:20 UTC, CeEv requested changes

2023-02-20 08:20 UTC, CeEv commented on src/security/authentication.js
> +		console.log(params);
remove console

2023-02-20 08:20 UTC, CeEv commented on src/security/authentication.js
> +		params += (req.query || {}).read === 'false' ? '?read=false' : '?read=true';
maybe a option
const { read, write, admin } = req.query || {};

2023-02-20 14:13 UTC, CeEv approved these changes

2023-02-23 16:23 UTC, merged