BC-7024-migration-to-ionos-postgres-dev
hpi-schul-cloud/schulcloud-calendar pull request #160
Opened 2024-04-05 13:32 UTC by YannickEvers

# Description
Overwrite database config/credentials when `WITH_BRANCH_POSTGRES_DB_MANAGEMENT` is enabled.
Belongs to https://github.com/hpi-schul-cloud/dof_app_deploy/pull/834
Should be merged first.

## Links to Tickets or other pull requests
[OPS-6241](https://ticketsystem.dbildungscloud.de/browse/OPS-6241)
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/834

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-04-08 06:42 UTC, simoncolincap commented on ansible/roles/schulcloud-calendar-init/tasks/main.yml
> +    when: WITH_CALENDAR_INIT and calendar_init_job_present.resources|length == 0
Why is this needed? As I understand it if the job is already present it won't run again anyway

2024-04-08 07:44 UTC, YannickEvers commented on ansible/roles/schulcloud-calendar-init/tasks/main.yml
> +    when: WITH_CALENDAR_INIT and calendar_init_job_present.resources|length == 0
The template specs are immutable. So if these changes are rolled out on an existing branch (should still be avoided, because the data of the old kubernetes internal database doesn't get migrated automatically), it would cause a failure.

2024-04-09 09:22 UTC, simoncolincap approved these changes

2024-04-09 11:09 UTC, mamutmk5 requested changes

2024-04-09 11:09 UTC, mamutmk5 commented on ansible/roles/schulcloud-calendar-core/templates/deployment.yml.j2
> +            name: pg-calendar-secret
The double secretRef is not allowed by the definition of Kubernetes Objects and cann produce uncleare out come

2024-04-11 13:31 UTC, YannickEvers commented on ansible/roles/schulcloud-calendar-core/templates/deployment.yml.j2
> +            name: pg-calendar-secret
Discussed this part. It's correctly defined that way.

2024-04-11 13:35 UTC, mamutmk5 approved these changes

2024-04-12 08:23 UTC, mamutmk5 requested changes
sorry must diskus this soulution with @Loki-Afro

2024-04-23 14:04 UTC, mamutmk5 approved these changes

2024-04-25 14:50 UTC, merged