Feature/ops 1474/push develop latest
hpi-schul-cloud/schulcloud-calendar pull request #49
Opened 2020-10-23 11:36 UTC by CeEv

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2020-10-23 11:55 UTC, janrenz approved these changes
develop must not be in quotes?

2020-10-23 14:29 UTC, mamutmk5 requested changes

2020-10-23 14:29 UTC, mamutmk5 commented on Makefile
> +	docker tag $(DOCKER_TAG_OPTIONS) $(DOCKER_IMAGE_NAME) $(DOCKER_REPO_NAME)_latest
the docker hube repo $(DOCKER_REPO_NAME)_latest dosn't exist

2020-10-23 14:29 UTC, mamutmk5 commented on Makefile
> +	docker push $(DOCKER_PUSH_OPTIONS) $(DOCKER_REPO_NAME)_latest
the docker hube repo $(DOCKER_REPO_NAME)_latest dosn't exist

2020-10-23 14:46 UTC, mamutmk5 approved these changes

2020-10-28 07:54 UTC, janrenz approved these changes

2020-10-28 07:54 UTC, merged