SC-8512: delete events by scope
hpi-schul-cloud/schulcloud-calendar pull request #65
Opened 2021-01-28 13:47 UTC by mwolowyk-cap

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-02-01 11:16 UTC, CeEv requested changes

2021-02-01 11:16 UTC, CeEv commented on src/config.js
> +exports.SPECIAL_API_KEY = process.env.SPECIAL_API_KEY || 'example';
A calendar API key already exist. Why using a different for this?

2021-02-01 11:16 UTC, CeEv commented on src/queries/events/constants.js
> +    '"last-modified"'
Is the ' "   " ' needed?

2021-02-01 11:16 UTC, CeEv commented on src/routes/events.js
> +			sendNotification.forDeletedEvent(
Notification do not work at the moment.

2021-02-01 11:16 UTC, CeEv commented on src/services/events/deleteDuplicatedEvents.js
> +};
linter: please add line break at the end

2021-02-01 11:16 UTC, CeEv commented on src/queries/events/deleteEvents.js
> +	const query = `DELETE FROM events where id in (
I am not sure if i understand what is is do. But for one scope in the most situations exist more the one event. One for each time entry in course. For what it should use? To cleanup something like a migration in the database, or as regular route in production?

2021-02-01 11:16 UTC, CeEv commented on src/services/events/deleteEventWithScope.js
> +};
please add a line break at the end

2021-02-01 12:30 UTC, mwolowyk-cap commented on src/queries/events/constants.js
> +    '"last-modified"'
yes. Because it is a column name with the hyper. It should add it to the query as INSERT INTO (...., x-fields, "last-modified"

2021-02-01 12:31 UTC, mwolowyk-cap commented on src/queries/events/deleteEvents.js
> +	const query = `DELETE FROM events where id in (
it should be called by the migration to clean up duplicated course events.

2021-02-01 12:31 UTC, mwolowyk-cap commented on src/routes/events.js
> +			sendNotification.forDeletedEvent(
Ok. I wondered, why I don't get any. Should I remove this code then?

2021-02-01 12:33 UTC, mwolowyk-cap commented on src/config.js
> +exports.SPECIAL_API_KEY = process.env.SPECIAL_API_KEY || 'example';
This should be hopefully a one time migration action. When the migration is done, the devops have to delete the key, so this action cannot be executed anymore.

2021-02-01 12:49 UTC, CeEv commented on src/config.js
> +exports.SPECIAL_API_KEY = process.env.SPECIAL_API_KEY || 'example';
Can we please rename like MIGRATION_CALENDAR_API_KEY ir so? Special is unspecific.

2021-02-01 12:53 UTC, CeEv commented on src/queries/events/deleteEvents.js
> +	const query = `DELETE FROM events where id in (
Can you please give me an example? I read the test, but the tested cases are valid data for courses. They can have multiple events for one scopeId and it should not remove them. 
Or remove this events only if start + end + scopeId is matched?

2021-02-01 12:54 UTC, CeEv commented on src/routes/events.js
> +			sendNotification.forDeletedEvent(
Yes please, or comment out.

2021-02-02 10:52 UTC, mwolowyk-cap commented on src/queries/events/deleteEvents.js
> +	const query = `DELETE FROM events where id in (
When the course is updated all course events are deleted and then new course events are created again. Due to eventual consistancy the deletion didn't work well. So we have not deleted events in the database and new events in the database. It means that only events, which were created by the last update request are valid. Everything else are duplicates. 
We take the max(last update) value and since other events for the same course came in multiple requests it will take some time for processing. Let's consider 20 seconds. 
It means that valid events are events which were created within 20 seconds before maximal last updated value for the corresponding courseId.

2021-02-02 11:59 UTC, mwolowyk-cap commented on src/config.js
> +exports.SPECIAL_API_KEY = process.env.SPECIAL_API_KEY || 'example';
ok

2021-02-02 11:59 UTC, mwolowyk-cap commented on src/routes/events.js
> +			sendNotification.forDeletedEvent(
ok

2021-02-02 14:38 UTC, closed without merging