add versioned basepath
hpi-schul-cloud/schulcloud-calendar pull request #83
Opened 2021-08-18 08:22 UTC by tofixx

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-08-18 13:12 UTC, virgilchiriac approved these changes

2021-08-24 08:38 UTC, mamutmk5 requested changes

2021-08-24 08:38 UTC, mamutmk5 commented on ansible/roles/schulcloud-calendar/templates/configmap.yml.j2
>    SCHULCLOUD_ALL_SCOPES_FOR_TOKEN: "http://api-svc:3030/resolve/scopes/"
What is her with api?
```suggestion
  SCHULCLOUD_ALL_USERS_FOR_UUID: "http://api-svc:3030/api/v1/resolve/users/"
  SCHULCLOUD_ALL_SCOPES_FOR_TOKEN: "http://api-svc:3030/api/v1/resolve/scopes/"
```

2021-08-24 08:38 UTC, mamutmk5 commented on package.json
> +  "version": "25.9.1",
If new version then it's 26.9.0 or 25.6.2 and not 25.9.1

2021-08-24 08:38 UTC, mamutmk5 commented on package-lock.json
> +  "version": "25.9.1",
If new version then it's 26.9.0 or 25.6.2 and not 25.9.1

2021-08-24 08:38 UTC, mamutmk5 commented on CHANGELOG.md
> +## [26.9.1] - 2021-08-18
If new version then it's 26.9.0 or 25.6.2

2021-08-24 08:56 UTC, mamutmk5 approved these changes

2021-08-24 11:02 UTC, merged