bc-111 wait for postgres to spin up
hpi-schul-cloud/schulcloud-calendar pull request #90
Opened 2021-09-28 13:22 UTC by Loki-Afro

wait for postgres to spin up

2021-09-29 08:17 UTC, mamutmk5 requested changes

2021-09-29 08:17 UTC, mamutmk5 commented on ansible/roles/schulcloud-calendar/templates/configmap_file_init_db.yml.j2
> +    done
Do not work how it shoud be.
The PostgreSQL Server requiers an password.
```suggestion
    echo $DB_PASSWORD > .pgpass
    until psql -h $DB_HOST -U $DB_USERNAME -w -d $DB_HOST -c "select 1" > /dev/null 2>&1; do
      echo "Waiting for postgres server..."
      sleep 1
    done
```

2021-09-29 08:46 UTC, Loki-Afro commented on ansible/roles/schulcloud-calendar/templates/configmap_file_init_db.yml.j2
> +    done
this works because the passsword is already set in the env vars, otherwise line 18 would fail

2021-10-01 09:36 UTC, mamutmk5 approved these changes

2021-10-01 09:38 UTC, merged