BC-654 use reusable workflows for auto deployment
hpi-schul-cloud/schulcloud-calendar pull request #93
Opened 2021-11-10 16:28 UTC by alriese

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity <sub><sup>details [on Confluence](https://docs.schul-cloud.org/x/2S3GBg)</sup></sub>

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

### Link to Definiton of Done

More and detailed information on the _definition of done_ can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=92831762)

2021-11-12 14:48 UTC, virgilchiriac requested changes

2021-11-12 14:48 UTC, virgilchiriac commented on .github/workflows/push.yml
> +
could add docker buildx also
```suggestion
- name: Set up Docker Buildx
        if: ${{ env.IMAGE_EXISTS == 0 }}
        uses: docker/setup-buildx-action@v1
```

2021-11-12 14:48 UTC, virgilchiriac commented on .github/workflows/push.yml
> +      - name: Build and push ${{ github.repository }}
```suggestion
      - name: Build and push ${{ github.repository }}
        if: ${{ env.IMAGE_EXISTS == 0 }}
```

2021-11-12 14:48 UTC, virgilchiriac commented on .github/workflows/push.yml
> +
branch name job missing
```suggestion
  branch_name:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
```

2021-11-15 09:32 UTC, mamutmk5 requested changes

2021-11-15 09:32 UTC, mamutmk5 commented on .github/workflows/push.yml
> +
If you change the workflow to this way please remove Please remove https://github.com/hpi-schul-cloud/schulcloud-calendar/blob/BC-654/.github/workflows/main.yml

2021-11-15 12:52 UTC, mamutmk5 approved these changes

2021-11-15 13:11 UTC, virgilchiriac approved these changes

2021-11-15 13:15 UTC, merged